name: Deploy Theme
on:
  push:
    branches:
      - master
jobs:
  deploy_to_onlythepixel:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: TryGhost/action-deploy-theme@v1.2.1
        with:
          api-url: ${{ secrets.ONLYTHEPIXEL_GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.ONLYTHEPIXEL_GHOST_ADMIN_API_KEY }}
          theme-name: "ectoplasm-master"
  deploy_to_genomagames:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: TryGhost/action-deploy-theme@v1.2.1
        with:
          api-url: ${{ secrets.GENOMAGAMES_GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GENOMAGAMES_GHOST_ADMIN_API_KEY }}
          theme-name: "ectoplasm-master"
